services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:17rc1-alpine
    environment:
      - POSTGRES_USER=npbankadmin
      - POSTGRES_PASSWORD=ilovenullsec2024
      - POSTGRES_DB=bankdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
